logging:
  level:
    org.springframework.web: ERROR
    com.howtodoinjava: DEBUG
    org.hibernate: ERROR
security:
  basic:
    enabled: false
management:
  endpoint:
    shutdown:
      enabled: true
    info:
      enabled: true
server:
  port: 9090
book:
  bookId: 101
laptop:
  processorName: Apple Silicon
  version: 22
  operatingSystem: MAC Big Sur

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/testdb;AUTO_SERVER=TRUE;MODE=Oracle
    driverClassName: org.h2.Driver
    username: sa
    password:
    database-platform: org.hibernate.dialect.H2Dialect